French translation fix
djGrrr/8311-was-110-firmware-builder pull request #18
Opened 2024-10-23 20:37 UTC by clementperon

2024-10-23 20:37 UTC, clementperon commented
@TeaRex-coder

2024-10-25 13:03 UTC, djGrrr commented
I've merged the other french translation updates, can you rebase your changes and apply any fixes as necessary? Thanks

2024-10-25 14:00 UTC, clementperon commented
@djGrrr rebased

2024-10-25 15:50 UTC, djGrrr commented
@TeaRex-coder @akhamar would you guys be able to look over these translation updates and comment? Thanks

@clementperon can you check the comments I've made?

2024-10-25 21:43 UTC, TeaRex-coder commented
Sure, I can have a look at them

2024-10-25 21:52 UTC, TeaRex-coder commented
The translations look good to me. Some are typos/grammar fixes, and others make the translations less literal to keep their original meaning.

2024-10-27 14:19 UTC, djGrrr requested changes

2024-10-27 14:27 UTC, clementperon commented on i18n/po/8311.fr.po
> +msgstr "Active un démon de surveillance Reverse ARP qui ajoutera automatiquement les entrées ARP à partir de l'addresse MAC des paquets reçus. Cela peut aider à accéder à l'interface de gestion sans
You're right, I have double check and it sais it is a common mistake. As a French I can confirm it, thanks!
I will revert this

2024-10-27 14:32 UTC, clementperon commented on i18n/po/8311.fr.po
> +msgstr "Active un démon de surveillance Reverse ARP qui ajoutera automatiquement des entrées ARP à partir des adresses MAC des paquets reçus. Cela peut aider à accéder à l'interface de gestion sans u
Thanks for the explanation, shouldn't this be called Dynamic ARP Inspection or Dynamic ARP Table Population ?

2024-10-27 14:34 UTC, clementperon commented on i18n/po/8311.fr.po
> +msgstr "Active un démon de surveillance Reverse ARP qui ajoutera automatiquement des entrées ARP à partir des adresses MAC des paquets reçus. Cela peut aider à accéder à l'interface de gestion sans u
I'm not a native english speaker, but seeing "Reverse ARP Monitoring" I understood "RARP Monitoring"

2024-10-27 14:43 UTC, djGrrr commented on i18n/po/8311.fr.po
> +msgstr "Active un démon de surveillance Reverse ARP qui ajoutera automatiquement des entrées ARP à partir des adresses MAC des paquets reçus. Cela peut aider à accéder à l'interface de gestion sans u
You're probably right, it may make more sense to change the name of it.

2024-10-27 15:03 UTC, clementperon commented on i18n/po/8311.fr.po
> +msgstr "Surveillance Reverse ARP"
I have reverted it

2024-10-27 15:04 UTC, clementperon commented on i18n/po/8311.fr.po
> +msgstr "Active un démon de surveillance Reverse ARP qui ajoutera automatiquement des entrées ARP à partir des adresses MAC des paquets reçus. Cela peut aider à accéder à l'interface de gestion sans u
OK I will revert my changes on this part so this MR could be merged.

2024-10-27 16:05 UTC, djGrrr approved these changes

2024-10-27 16:08 UTC, merged

2024-10-27 16:09 UTC, djGrrr commented
Thanks for your contribution, this has been merged and will be in the next release.